---
# CONNECTED_ENDPOINTS.yml
# Definition of connected endpoints in the fabric.

port_profiles:
  - profile: ESX-HOSTS
    mode: trunk
    vlans: 11,12
    spanning_tree_portfast: edge
    port_channel:
      mode: active

servers:

# Alternative Way, Switch-Port-Centric:
#  - switches:
#      - s2-host[12]      # regex to match multiple hosts
#    switch_ports:
#      - Ethernet4-5      # match multiple ports if applicable
#    profile: ESX-HOSTS   # assign profile or define attributes one by one, or mix it