---
# CONNECTED_ENDPOINTS.yml
# Definition of connected endpoints in the fabric.

port_profiles:
  - profile: ESX-HOSTS
    mode: trunk
    vlans: 11,12
    spanning_tree_portfast: edge
    port_channel:
      mode: active
  - profile: SERVER-GROUP1
    mode: access
    vlans: 11
    spanning_tree_portfast: edge
    port_channel:
      mode: active

servers:
  - name: s2-host1
    adapters:
      - endpoint_ports: [Ethernet1,Ethernet2]
        switch_ports: [Ethernet4,Ethernet4]
        switches: [s2-leaf1,s2-leaf2]
        profile: SERVER-GROUP1
        
  - name: s2-host2
    adapters:
      - endpoint_ports: [Ethernet1,Ethernet2]
        switch_ports: [Ethernet4,Ethernet4]
        switches: [s2-leaf3,s2-leaf4]
        profile: SERVER-GROUP1

# Alternative Way, Switch-Port-Centric:
#  - switches:
#      - s2-host[12]      # regex to match multiple hosts
#    switch_ports:
#      - Ethernet4-5      # match multiple ports if applicable
#    profile: ESX-HOSTS   # assign profile or define attributes one by one, or mix it