---
# FABRIC.yml
# General definition of the fabric and its properties.

fabric_name: FABRIC

default_interfaces:
  - types: [spine]
    platforms: [default]
  - types: [l3leaf]
    platforms: [default]

mgmt_interface: Management0
mgmt_interface_vrf: default
mgmt_interface_description: null

management_eapi:
  enabled: true

custom_structured_configuration_enable_password:
  disabled: false