---
# LEAFS.yml
# Definition of the leafs in the fabric.

type: l3leaf

l3leaf:
  defaults:
    platform: cEOS-LAB
    loopback_ipv4_pool: 10.255.0.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.255.1.0/24
    mlag_peer_ipv4_pool: 10.255.254.0/24



    mlag_peer_l3_vlan: 0
    virtual_router_mac_address: 00:1c:73:00:dc:02



    
  node_groups: